common/models/Post.php
<?php

namespace common\models;

use floor12\files\models\File;
use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "post".
 *
 * @property int $id
 * @property string $title
 * @property string|null $content
 * @property string|null $description
 * @property int|null $status
 * @property int|null $publish_date
 * @property int|null $created_at
 * @property int|null $updated_at
 * @property int|null $created_by
 * @property int|null $updated_by
 * @property File|null $post_image
 */
class Post extends ActiveRecord
{
    const STATUS_DRAFT = 0;
    const STATUS_PUBLISH = 1;
    const STATUS_HIDDEN = 2;


    function behaviors()
    {
        return [
            'timestamp' => [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
            ],
            'blameable' => [
                'class' => BlameableBehavior::class,
                'createdByAttribute' => 'created_by',
                'updatedByAttribute' => 'updated_by',
            ],
            'files' => [
                'class' => 'floor12\files\components\FileBehaviour',
                'attributes' => [
                    'post_image' => [
                        'ratio' => '406/250'
                    ],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'post';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'content', 'description'], 'required'],
            ['post_image', 'file', 'extensions' => ['jpg', 'png', 'jpeg', 'gif'], 'maxFiles' => 1],
            [['title', 'content', 'description'], 'string'],
            [['status', 'created_at', 'publish_date', 'updated_at', 'created_by', 'updated_by'], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Заголовок',
            'content' => 'Контент',
            'description' => 'Короткое описание',
            'status' => 'Статус',
            'publish_date' => 'Опубликовано',
            'created_at' => 'Создано',
            'updated_at' => 'Обновлено',
            'created_by' => 'Создал',
            'updated_by' => 'Обновил',
            'post_image' => 'Изображение',
        ];
    }

    public static function getStatusList()
    {
        return [self::STATUS_DRAFT => 'Черновик', self::STATUS_PUBLISH => 'Опубликован', self::STATUS_HIDDEN => 'Скрыт'];
    }

    public function publish()
    {
        $this->status = self::STATUS_PUBLISH;
        $this->publish_date = time();
        return $this->save();
    }

    public function hide()
    {
        $this->publish_date = null;
        $this->status = self::STATUS_HIDDEN;
        return $this->save();
    }
}

backend/controllers/PostController.php
<?php

namespace backend\controllers;

use floor12\files\logic\FileCreateFromInstance;
use Yii;
use common\models\Post;
use common\models\search\PostSearch;
use yii\filters\AccessControl;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * PostController implements the CRUD actions for Post model.
 */
class PostController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => [
                            'delete',
                        ],
                        'allow' => true,
                        'roles' => ['superadmin'],
                    ],
                    [
                        'actions' => [
                            'create',
                            'update',
                            'view',
                            'index',
                            'publish',
                            'restore',
                            'hide',
                            'upload-img',
                        ],
                        'allow' => true,
                        'roles' => ['moderator'],
                    ]
                ],
            ],
        ];
    }

    /**
     * Lists all Post models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Post model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Post model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Post();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if ((integer)$model->status === Post::STATUS_PUBLISH) {
                $model->publish();
            }
            return $this->redirect(['index', 'id' => $model->id]);
        } else {
//            return var_dump($model->getErrors());
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Post model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if ((integer)$model->status === Post::STATUS_PUBLISH) {
                $model->publish();
            }
            return $this->redirect(['index', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Post model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Post model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Post the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Post::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionPublish($id)
    {
        $model = $this->findModel($id);
        if (!$model->publish()){
            var_dump($model->getErrors());
        }
        return $this->redirect(['index']);
    }

    public function actionHide($id)
    {
        $model = $this->findModel($id);
        if (!$model->hide()){
            var_dump($model->getErrors());
        }
        return $this->redirect(['index']);
    }

    public function actionRestore($id)
    {
        $this->findModel($id)->publish();
        return $this->redirect(['index']);
    }

    public function actionUploadImg($CKEditorFuncNum)
    {
        $file = UploadedFile::getInstanceByName('upload');
        if ($file){
            $data = array_merge(
                [
                    'modelClass' => 'common\\models\\Post',
                    'attribute' => 'files',
                    'mode' => 'multi',
                    'ratio' => 0
                ],
                Yii::$app->request->post()
            );

            $model = Yii::createObject(FileCreateFromInstance::class, [
                $file,
                $data,
                Yii::$app->user->identity,
            ])->execute();


            if ($model->errors) {
                throw new BadRequestHttpException('Ошибки валидации модели');
            }

            if ($model->save()){
                $ratio = Yii::$app->request->post('ratio', null);

                $view = Yii::$app->request->post('mode') === 'single' ? "_single" : "_file";

                $result = $this->renderAjax('@floor12/files/views/default/' . $view, [
                    'model' => $model,
                    'ratio' => $ratio
                ]);

                return '<script type="text/javascript">
                            window.parent.CKEDITOR.tools.callFunction("'.$CKEditorFuncNum.'", "' . $model->href.'", "");
                       </script>';

            } else
                return "Возникла ошибка при загрузке файла\n";
        } else
            return "Файл не загружен\n";
    }

}

backend/views/post/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Post */
/* @var $form yii\widgets\ActiveForm */
?>
<style>
    .post-form img {
        max-height: 300px;
    }
</style>
<div class="post-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>
    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'title')->textarea(['rows' => 1]) ?>

            <?= $form->field($model, 'description')->textarea(['rows' => 4]) ?>

            <?= $form->field($model, 'status')->dropDownList(\common\models\Post::getStatusList()) ?>

        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'post_image')->widget(floor12\files\components\FileInputWidget::class) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?= $form->field($model, 'content')->widget(\mihaildev\ckeditor\CKEditor::class, [
                'editorOptions' => [
                    'preset' => 'full', //разработанны стандартные настройки basic, standard, full данную возможность не обязательно использовать
                    'inline' => false, //по умолчанию false
                    'filebrowserUploadUrl' => \yii\helpers\Url::to(['/post/upload-img']),
                    'filebrowserImageUploadUrl' => \yii\helpers\Url::to(['/post/upload-img']),
                    'allowedContent' => true
                ]
            ]) ?>
            <div class="form-group">
                <?= Html::submitButton($model->isNewRecord ? 'Создать' : 'Обновить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
            </div>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/post/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\search\PostSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="post-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'content') ?>

    <?= $form->field($model, 'status') ?>

    <?= $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'author_id') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/post/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Post */

$this->title = 'Создать пост';
$this->params['breadcrumbs'][] = ['label' => 'Посты', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="post-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/post/index.php
<?php

use common\models\Post;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\search\PostSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Посты';
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="post-index">

    <p>
        <?= Html::a('Создать пост', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'title:ntext',
            [
                'attribute' => 'status',
                'filter' => Html::activeDropDownList(
                    $searchModel,
                    'status',
                    Post::getStatusList(),
                    ['class' => 'form-control', 'prompt' => 'Статус']
                ),
                'value' => function($model) {
                    $arrayTranslate = Post::getStatusList();
                    return $arrayTranslate[$model->status];
                }
            ],
            [
                'attribute' => 'created_at',
                'filter' => \kartik\date\DatePicker::widget([
                    'model' => $searchModel,
                    'attribute' => 'created_at',
                    'language' => 'ru',
                    'options' => [
                        'class' => 'form-control',
                        'placeholder' => 'Дата создания',
                        'autocomplete' => 'off',
                    ],
                ]),
                'value' => function($model) {
                    return date('d.m.Y H:i:s', $model->created_at);
                }
            ],
            [
                'attribute' => 'publish_date',
                'filter' => \kartik\date\DatePicker::widget([
                    'model' => $searchModel,
                    'attribute' => 'publish_date',
                    'language' => 'ru',
                    'options' => [
                        'class' => 'form-control',
                        'placeholder' => 'Дата публикации',
                        'autocomplete' => 'off',
                    ],
                ]),
                'value' => function($model) {
                    if ($model->publish_date === null) {
                        return 'не задано';
                    }
                    return date('d.m.Y H:i:s', $model->publish_date);
                }
            ],
            [
                'header' => 'Действия',
                'value' => function($model) {
                    if ($model->status === Post::STATUS_DRAFT) {
                        return Html::a('Опубликовать', ['publish', 'id' => $model->id], ['class' => 'label label-success']);
                    }
                    if ($model->status === Post::STATUS_PUBLISH) {
                        return Html::a('Скрыть', ['hide', 'id' => $model->id], ['class' => 'label label-danger']);
                    }
                    if ($model->status === Post::STATUS_HIDDEN) {
                        return Html::a('Показать', ['publish', 'id' => $model->id], ['class' => 'label label-primary']);
                    }
                },
                'format' => 'raw',
                'visible' => Yii::$app->user->can('moderator')
            ],

            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{update}{delete}',
                'buttonOptions' => ['class' => 'btn btn-default'],
            ],
        ],
    ]); ?>
</div>

backend/views/post/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Post */

$this->title = 'Изменить пост: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Посты', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Изменить';
?>
<div class="post-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/post/view.php
<?php

use common\models\Post;
use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Post */

$this->title = 'Предварительный просмотр';
$this->params['breadcrumbs'][] = ['label' => 'Посты', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="post-view">

    <p>
        <?= Html::a('Изменить', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?php
        if ($model->status === Post::STATUS_DRAFT) {
            echo Html::a('Опубликовать', ['publish', 'id' => $model->id], ['class' => 'btn btn-success']);
        }
        if ($model->status === Post::STATUS_PUBLISH) {
            echo Html::a('Скрыть', ['hide', 'id' => $model->id], ['class' => 'btn btn-danger']);
        }
        if ($model->status === Post::STATUS_HIDDEN) {
            echo Html::a('Показать', ['publish', 'id' => $model->id], ['class' => 'btn btn-primary']);
        }
        ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?php
    $title = $model->title;
    $description = $model->content;
    ?>
    <div class="post-preview">
        <div class="box">
            <div class="post-title">
                <h1>
                    <?=$title?>
                </h1>
            </div>
            <div class="post-content">
                <?= $description ?>
            </div>
        </div>
    </div>


</div>