common/models/Slider.php
<?php

namespace common\models;

use floor12\files\models\File;
use Yii;

/**
 * This is the model class for table "slider".
 *
 * @property int $id
 * @property string|null $title
 * @property string|null $url
 * @property int|null $order
 * @property int $status
 * @property File $image
 * @property File $image_mobile
 */
class Slider extends \yii\db\ActiveRecord
{

    const STATUS_ACTIVE = 1;
    const STATUS_INACTIVE = 0;

    function behaviors()
    {
        return [
            'files' => [
                'class' => 'floor12\files\components\FileBehaviour',
                'attributes' => [
                    'image' => [
                        'ratio' => '1280/400'
                    ],
                    'image_mobile' => [
                        'ratio' => '375/400'
                    ],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'slider';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title'], 'required'],
            [['title', 'url'], 'string'],
            ['image', 'file', 'extensions' => ['jpg', 'png', 'jpeg', 'gif'], 'maxFiles' => 1],
            ['image_mobile', 'file', 'extensions' => ['jpg', 'png', 'jpeg', 'gif'], 'maxFiles' => 1],
            [['order', 'status'], 'integer'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Заголовок',
            'url' => 'Ссылка',
            'order' => 'Порядок',
            'status' => 'Статус',
            'image' => 'Изображение',
            'image_mobile' => 'Изображение для телефонов',
        ];
    }

    public static function getStatusList()
    {
        return [
            self::STATUS_ACTIVE => 'вкл',
            self::STATUS_INACTIVE => 'выкл',
        ];
    }

    public function enable()
    {
        $this->status = self::STATUS_ACTIVE;
        return $this->save();
    }

    public function disable()
    {
        $this->status = self::STATUS_INACTIVE;
        $this->order = null;
        return $this->save();
    }

    public function setOrder($ord)
    {
        $this->order = $ord;
        return $this->save();
    }
}

backend/controllers/SliderController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Slider;
use common\models\search\SliderSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SliderController implements the CRUD actions for Slider model.
 */
class SliderController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => [
                            'delete',
                        ],
                        'allow' => true,
                        'roles' => ['superadmin'],
                    ],
                    [
                        'actions' => [
                            'create',
                            'update',
                            'view',
                            'index',
                            'enable',
                            'disable',
                            'order-up',
                            'order-down',
                        ],
                        'allow' => true,
                        'roles' => ['moderator'],
                    ]
                ],
            ],
        ];
    }

    /**
     * Lists all Slider models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SliderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Slider model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Slider model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Slider();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Slider model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Slider model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Slider model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Slider the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Slider::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }


    public function actionDisable($id)
    {
        $model = $this->findModel($id);
        if(!$model->disable()){
            Yii::$app->session->setFlash('danger', 'Что то пошло не так... Повторите попытку позже');
        } else {
            Yii::$app->session->setFlash('success', 'Слайд отключен');
        }

        return $this->redirect(['index']);
    }

    public function actionEnable($id)
    {
        if(!$this->findModel($id)->enable()){
            Yii::$app->session->setFlash('danger', 'Что то пошло не так... Повторите попытку позже');
        } else {
            Yii::$app->session->setFlash('success', 'Слайд включен');
        }
        return $this->redirect(['index']);
    }

    public function actionOrderUp($id)
    {
        $model = $this->findModel($id);
        $ord = $model->order - 1;
        $preModel = Slider::findOne(['status' => Slider::STATUS_ACTIVE, 'order' => $ord]);
        if ($preModel) {
            $preModel->setOrder($model->order);
        }
        if(!$model->setOrder($ord)){
            Yii::$app->session->setFlash('danger', 'Что то пошло не так... Повторите попытку позже');
        } else {
            Yii::$app->session->setFlash('success', 'Слайд перемещен');
        }

        return $this->redirect(['index']);
    }

    public function actionOrderDown($id)
    {
        $model = $this->findModel($id);

        $ord = $model->order + 1;
        $preModel = Slider::findOne(['status' => Slider::STATUS_ACTIVE, 'order' => $ord]);
        if ($preModel) {
            $preModel->setOrder($model->order);
        }
        if(!$model->setOrder($ord)){
            Yii::$app->session->setFlash('danger', 'Что то пошло не так... Повторите попытку позже');
        } else {
            Yii::$app->session->setFlash('success', 'Слайд перемещен');
        }
        return $this->redirect('index');
    }
}

backend/views/slider/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Slider */
/* @var $form yii\widgets\ActiveForm */
?>
<style>
    .floor12-files-widget-list img {
        max-height: 250px;
    }
</style>
<div class="slider-form">

    <?php $form = ActiveForm::begin(); ?>
    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'title')->textInput() ?>
            <?= $form->field($model, 'url')->textInput() ?>
            <div class="row">
                <div class="col-md-6">
                    <?= $form->field($model, 'order')->textInput(['type' => 'number', 'value' => $model->isNewRecord ? 0 : $model->order]) ?>
                </div>
                <div class="col-md-6">
                    <?= $form->field($model, 'status')->dropDownList(\common\models\Slider::getStatusList()) ?>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'image')->widget(floor12\files\components\FileInputWidget::class) ?>

            <?= $form->field($model, 'image_mobile')->widget(floor12\files\components\FileInputWidget::class) ?>
        </div>
    </div>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Добавить' : 'Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/slider/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\search\SliderSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="slider-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'url') ?>

    <?= $form->field($model, 'order') ?>

    <?= $form->field($model, 'status') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/slider/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Slider */

$this->title = 'Добавить слайд';
$this->params['breadcrumbs'][] = ['label' => 'Слайдер', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="slider-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/slider/index.php
<?php

use common\models\Slider;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\search\SliderSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Слайдер';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="slider-index">

    <p>
        <?= Html::a('Добавить слайд', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'title:ntext',
            'url:ntext',
            [
                'attribute' => 'order',
                'format' => 'raw',
                'value' => function ($model) {
                    if ($model->status === Slider::STATUS_INACTIVE) return '';
                    $html = Html::a('<i class="glyphicon glyphicon-chevron-up"></i> ', ['slider/order-up', 'id' => $model->id], ['class' => $model->order === 0 ? 'disabled' : '']);
                    $html .= $model->order;
                    $html .= Html::a(' <i class="glyphicon glyphicon-chevron-down"></i>', ['slider/order-down', 'id' => $model->id]);
                    return $html;
                }
            ],
            [
                'attribute' => 'status',
                'format' => 'raw',
                'filter' => Html::activeDropDownList($searchModel, 'status', Slider::getStatusList(), ['class' => 'form-control', 'prompt' => 'Все']),
                'value' => function ($model) {
                    if ($model->status === Slider::STATUS_ACTIVE) {
                        return Html::tag('span', 'ВКЛ', [
                            'class' => 'label label-success',
                        ]);
                    }
                    return Html::tag('span', 'ВЫКЛ', [
                        'class' => 'label label-danger',
                    ]);
                }
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{action} {update} {delete}',
                'buttons' => [
                    'action' => function ($url, $model, $key) {
                        if ($model->status === Slider::STATUS_ACTIVE) {
                            return Html::a('Отключить', ['disable', 'id' => $model->id], [
                                'class' => 'label label-danger',
                                'title' => 'Нажмите, чтобы включить.',
                                'data-confirm' => 'Вы действительно хотите отключить данный элемент?'
                            ]);
                        }
                        return Html::a('Включить', ['enable', 'id' => $model->id], [
                            'class' => 'label label-success',
                            'title' => 'Нажмите, чтобы отключить.'
                        ]);
                    },
                ],
                'buttonOptions' => ['class' => 'btn btn-default']
            ],
        ],
    ]); ?>


</div>

backend/views/slider/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Slider */

$this->title = 'Редактировать слайд: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Слайдеры', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Редактирование';
?>
<div class="slider-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/slider/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Slider */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Sliders', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="slider-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'title:ntext',
            'url:ntext',
            'order',
            'status',
        ],
    ]) ?>

</div>