backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use common\models\File;
use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\models\AreaInfo;
use common\models\ContactForm;
use common\models\Page;
use common\models\Post;
use common\models\Slider;
use frontend\models\ResendVerificationEmailForm;
use frontend\models\VerifyEmailForm;
use Yii;
use yii\base\Exception;
use yii\base\InvalidArgumentException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use yii\web\NotFoundHttpException;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $sliders = Slider::find()->where(['status' => Slider::STATUS_ACTIVE])->orderBy('order')->all();
        $pages = Page::find()->where(['status' => Page::STATUS_PUBLISH, 'on_main_page' => 1])->all();

        return $this->render('index', ['sliders' => $sliders, 'pages' => $pages]);
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact($send_to)
    {
        $data = Yii::$app->request->post('ContactForm', false);
        if ($data) {
            $model = new ContactForm();
            $model->scenario = $data['scenario'];
            if ($model->load(Yii::$app->request->post()) && $model->contact($send_to)) {
                switch ($model->scenario) {
                    case ContactForm::SCENARIO_CONTACT:
                        $message = 'Ваше сообщение отправлено.';
                        break;
                    default: $message = 'Ваше действие имело успех.';

                }
                Yii::$app->session->setFlash('success', $message);

                return $this->redirect(Yii::$app->request->referrer);
            }
        }

        Yii::$app->session->setFlash('danger', 'Что то пошло не так... Повторите попытку позже.');

        return $this->redirect(Yii::$app->request->referrer);
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Displays Contacts page.
     *
     * @return mixed
     */
    public function actionContacts()
    {
        if (($model = Page::findOne(['slug' => 'kontakty'])) !== null) {
            return $this->render('page', ['model' => $model]);
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * Displays post page.
     *
     * @return mixed
     */
    public function actionPost($id)
    {
        $post = $this->findPost($id);
        return $this->render('post', ['post' => $post]);
    }


    /**
     * Displays Pages page.
     *
     * @return mixed
     */
    public function actionPage($id)
    {
        $model = $this->findPage($id);

        return $this->render('page', ['model' => $model]);
    }

    /**
     * Displays news page.
     *
     * @return mixed
     */
    public function actionNews()
    {
        $posts = Post::findAll(['status' => Post::STATUS_PUBLISH]);
        return $this->render('news', ['posts' => $posts]);
    }

    protected function findPost($id)
    {
        if (($model = Post::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    protected function findPage($id)
    {
        if (($model = Page::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionStatistics($form = 1)
    {
        $this->view->title = 'Статистика и списки поступающих';
        $isMobile = (integer)\Yii::$app->devicedetect->isMobile();
        $fileName = 'stat-'.$form . '-' . '0' . '-' . '0' . '-' . $isMobile;

        if (!file_exists(Yii::getAlias("@frontend")."/views/statistic/{$fileName}.php"))
            throw new NotFoundHttpException('The requested page does not exist.');

        if($isMobile){
            $this->view->registerJs("
            jQuery(document).ready(function () {
                jQuery('.spec-link').click(function (eo) {
                    jQuery(eo.target).next().slideToggle('fast');
                });
                jQuery('.minimize-descr').click(function (eo) {
                    jQuery(eo.target).parent().slideToggle('fast');
                });
                
            });
            ");
        }

        $content = $this->renderPartial('/statistic/' . $fileName);
        return $this->render('statistic', ['content' => $content]);
    }

    public function actionAbitsList($form = 1, $skillid = 0, $ext = 0, $she = 0, $sort = 0)
    {
        $this->view->title = 'Статистика и списки поступающих';
        $isMobile = (integer)\Yii::$app->devicedetect->isMobile();

        $fileName = "abits-list-1-{$form}-{$skillid}-{$ext}-{$she}-{$sort}--1-{$isMobile}";

        if (!file_exists(Yii::getAlias('@frontend') . "/views/statistic/{$fileName}.php"))
            throw new NotFoundHttpException('Не удалось найти сведений, зайдите позже');

        if($isMobile){
            $this->view->registerJs("
            jQuery(document).ready(function () {
                jQuery('.spec-link').click(function (eo) {
                    jQuery(eo.target).next().slideToggle('fast');
                });
                jQuery('.minimize-descr').click(function (eo) {
                    jQuery(eo.target).parent().slideToggle('fast');
                });
                
            });
            ");
        }

        $content = $this->renderPartial("/statistic/{$fileName}");
        return $this->render('statistic', ['content' => $content]);
    }

    public function actionZAbitsList($form = 1, $skillid = 0, $ext = 0, $she = 0, $sort = 0)
    {
        $this->view->title = 'Статистика и списки поступающих';
        $isMobile = (integer)\Yii::$app->devicedetect->isMobile();

        $params = [
            'f' => 1,
            'p' => 0,
            'rang' => 0,
            'withouthvost' => 1,
            'prog' => 0,
            'type' => 0,
            'att' => 0, // аттестат
            'she' => 0, //второе высшее
            'e' => 0, //сокращенка
            'withoutdeadline' => 0,
            'mobile' => $isMobile
        ];

//        if (!file_exists(Yii::getAlias('@frontend') . "/views/statistic/abits-list-{$form}-{$skillid}-{$ext}-{$she}-{$sort}"))
//            throw new NotFoundHttpException('The requested page does not exist.');

        $content = AreaInfo::getZList($params);

        $p1 = strpos($content, '<!-- begin -->');
        $p2 = strpos($content, '<!-- end -->');

        $content = mb_strcut($content, $p1, $p2-$p1);
        $content = str_replace('<table', '<table class="table table-bordered"', $content);

        return $this->render('statistic', ['content' => $content]);
    }

//    public function actionSoap()
//    {
//        $result = Yii::$app->soapClientManager->load('GetStringsPriema', []);
//        var_dump($result);
//        die;
//    }


    public function actionStatistic($form = 'ochnoe')
    {
        $data = [];

        $dir = Yii::getAlias('@frontend') . '/web/uploads/reports/' . $form . '/';
        if (file_exists($dir)) {
            $formNames = [
                'ochnoe' => 'очная',
                'zaochnoe' => 'заочная',
                'ochno-zaochnoe' => 'очно-заочная'
            ];

            $files = array_diff(scandir($dir), array('..', '.'));
            foreach ($files as $file){
                $fileName = $dir . $file;
                if (file_exists($fileName)) {
                    $content = file_get_contents($fileName);
                    $p1 = strpos($content, '<TABLE');
                    $p2 = strpos($content, '</TABLE>');

                    $content = mb_strcut($content, $p1, $p2-$p1+8);
                    $name = str_replace('_', ' ', $file);
                    $name = str_replace('.HTML', '', $name);
                    $name = str_replace('.html', '', $name);
                    $data[] = [
                        'name' => $name,
                        'content' => $content
                    ];
                }
            }
        } else {
//            throw new Exception('Информация по данной форме отсутствует');
            return $this->render('stat', ['data' => 'Информация по данной форме отсутствует']);
        }

        return $this->render('stat', ['data' => $data]);
    }
}

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/index.php
<?php

use common\models\Settings;
use common\widgets\ContactFormWidget\ContactFormWidget;
use kv4nt\owlcarousel\OwlCarouselWidget;
use mattan929\calendar\widgets\EventCalendarWidget\EventCalendarWidget;

$this->title = 'Курганский государственный университет - Приемная комиссия';

?>

<div class="row">
    <div class="slider">
        <?php
        OwlCarouselWidget::begin([
            'container' => 'div',
            'assetType' => OwlCarouselWidget::ASSET_TYPE_CDN,
            'containerOptions' => [
                'id' => 'slider',
                'class' => 'container-class owl-theme',
            ],
            'pluginOptions' => [
                'autoplay' => true,
                'autoplayTimeout' => 10000,
                'items' => 1,
                'margin' => 10,
                'nav' => true,
                'dots' => false,
                'center' => true,
                'merge' => true,
                'loop' => true,
                'navContainer' => '#slider',
                'navElement' => 'div',
                'navClass' => [
                    'slider-prev',
                    'slider-next'
                ],
                'navContainerClass' => 'owl-nav slider-nav',
                'navText' => [
                    '<i class="glyphicon glyphicon-menu-left"></i>',
                    '<i class="glyphicon glyphicon-menu-right"></i>'
                ],
                'itemsDesktop' => [1199, 1],
                'itemsDesktopSmall' => [979, 1],
                'responsive' => [
                    0 => [
                        'items' => 1,
                        'nav' => false,
                    ],
                    768 => [
                        'items' => 1,
                        'nav' => true,
                    ],
                ],
            ]
        ]);
        ?>
        <?php /** @var \common\models\Slider[] $sliders */
        foreach ($sliders as $slider): ?>
            <div class="item">
                <a href="<?= !empty($slider->url) ? $slider->url : '#' ?>">
                    <div class="slide"
                         style="height: 400px; background-image: url('<?= $slider->image ?>'); background-size: cover"></div>
                    <div class="slide-mobile"
                         style="height: 400px; background-image: url('<?= $slider->image_mobile ?>'); background-size: cover"></div>
                </a>
            </div>
        <?php endforeach; ?>
        <?php OwlCarouselWidget::end(); ?>
    </div>
</div>
<div class="">
    <h3 class="text-center">ГЛАВНЫЕ НОВОСТИ</h3>
    <div class="main-news">
        <?php
        OwlCarouselWidget::begin([
            'container' => 'div',
            'assetType' => OwlCarouselWidget::ASSET_TYPE_CDN,
            'containerOptions' => [
                'id' => 'main-news',
                'class' => 'container-class owl-theme',
            ],
            'pluginOptions' => [
                'autoplay' => true,
                'autoplayTimeout' => 10000,
                'items' => 1,
                'margin' => 20,
                'nav' => true,
                'dots' => false,
                'center' => true,
                'merge' => true,
                'loop' => true,
                'navContainer' => '#main-news',
                'navElement' => 'div',
                'navClass' => [
                    'slider-prev',
                    'slider-next'
                ],
                'navContainerClass' => 'owl-nav slider-nav',
                'navText' => [
                    '<i class="glyphicon glyphicon-menu-left"></i>',
                    '<i class="glyphicon glyphicon-menu-right"></i>'
                ],
                'itemsDesktop' => [1199, 1],
                'itemsDesktopSmall' => [979, 1],
                'responsive' => [
                    0 => [
                        'items' => 1,
                        'nav' => false,
                    ],
                    768 => [
                        'items' => 1,
                        'nav' => true,
                    ],
                ],
            ]
        ]);
        ?>

        <?= \common\widgets\NewsWidgets\NewsList::widget(['mode' => 'simple']) ?>

        <?php OwlCarouselWidget::end(); ?>
    </div>
    <a href="<?= \yii\helpers\Url::to(['site/news']) ?>"><u><h4 class="text-center">БОЛЬШЕ НОВОСТЕЙ</h4></u></a>

</div>
<div class="row">
    <h3 class="text-center">ПРИЁМ <?= date('Y')?></h3>
    <div class="main-page-block">
        <?php
        /** @var \common\models\Page[] $pages */
        foreach ($pages as $key => $page): ?>
            <?= $key%3 === 0 ? '<div class="clearfix"></div>' : '' ?>
            <div class="col-md-4">
                <div class="panel">
                    <div class="panel-header">
                        <a href="<?= \yii\helpers\Url::to(['site/page', 'id' => $page->id]) ?>">
                            <div class="flag-title">
                                <?= $page->title ?>
                            </div>
                            <div class="img-block">
                                <img src="<?= $page->image->getPreviewWebPath(396, 0, true) ?>" alt="">
                            </div>
                        </a>
                    </div>
                    <div class="panel-body">
                        <div class="text">
                            <ul class="list-unstyled">
                                <?php foreach ($page->links as $link):
                                    /** @var \common\models\LinkOnPage $link */?>
                                <li>
                                    <a href="<?= $link->urlToTarget?>" target="<?= $link->type ?>"><?= $link->title?></a>
                                </li>
                                <?php endforeach; ?>

                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>

<?= EventCalendarWidget::widget() ?>

<div class="row">
    <h3 class="text-center">ЗАДАЙТЕ ВОПРОС</h3>
    <div class="feedback-form" id="feedback-form">
        <?= ContactFormWidget::widget(['send_to' => Settings::getValue('notification-e-mail'), 'subject' => 'Форма обратной связи']) ?>
    </div>
</div>

frontend/views/site/news.php
<?php

/* @var $this \yii\web\View */
/* @var $posts \yii\db\ActiveQuery */

use common\widgets\NewsWidgets\NewsList;

$this->title = 'Новости';
$this->params['breadcrumbs'][] = ['label' => $this->title];

?>

<div class="news-page">

    <?= NewsList::widget(['news' => $posts, 'items' => 20, 'showmore' => true, 'withoutCategory' => true]) ?>
</div>

frontend/views/site/post.php
<?php

/* @var $this \yii\web\View */
/* @var $post \common\models\Post|null */

$this->title = $post->title;
$this->params['breadcrumbs'][] = ['label' => 'Новости', 'url' => ['/site/news']];
$this->params['breadcrumbs'][] = ['label' => \yii\helpers\StringHelper::truncate($this->title , 30) ];

?>
<div class=" page post-page">
    <div class="row">
        <div class="col-lg-9">
            <?= $post->content ?>
        </div>
        <div class="col-lg-3">
            <div class="date-block">
                <p>
                    <em>
                        Опубликовано:<br>
                        <?= Yii::$app->formatter->asDate($post->publish_date, 'dd MMMM Y hh:mm') ?>
                    </em>
                </p>
            </div>
            <div class="img-block">
                <a class="fancybox" data-fancybox="post-image" rel="group" href="<?= $post->post_image ?>">
                    <img src="<?= $post->post_image->getPreviewWebPath(282, 0, true) ?>"
                         alt="<?= $post->title ?>">
                </a>
            </div>
        </div>
    </div>
</div>

frontend/views/site/stat.php
<?php

/* @var $this \yii\web\View */
/* @var $data array */

use yii\bootstrap\Nav;

$this->title = 'Статистика и списки поступающих';
$this->params['breadcrumbs'][] = ['label' => $this->title];

?>

<div class="page">
    <STYLE TYPE="text/css">
        tr.R0 {
            height: 17px;
        }

        tr.R0 td.R0C0 {
            font-family: Times New Roman;
            font-size: 10pt;
            font-style: normal;
            font-weight: bold;
            text-align: center;
        }

        tr.R0 td.R2C0 {
            font-family: Times New Roman;
            font-size: 10pt;
            font-style: normal;
            font-weight: bold;
            text-align: left;
        }

        tr.R1 {
            height: 15px;
        }

        tr.R1 td.R1C0 {
            font-family: Times New Roman;
            font-size: 10pt;
            font-style: normal;
            text-align: center;
            vertical-align: middle;
        }

        tr.R14 {
            height: 16px;
        }

        tr.R14 td.R14C0 {
            font-family: Times New Roman;
            font-size: 9pt;
            font-style: normal;
            font-weight: bold;
            text-align: left;
            vertical-align: middle;
            padding-left: 16px;
        }

        tr.R16 {
            height: 65px;
        }

        tr.R16 td.R16C0 {
            font-family: Times New Roman;
            font-size: 10pt;
            font-style: normal;
            text-align: center;
            vertical-align: middle;
            border-left: #000000 1px solid;
            border-top: #000000 1px solid;
            border-bottom: #000000 1px solid;
            border-right: #000000 1px solid;
        }

        tr.R16 td.R16C2 {
            font-family: Times New Roman;
            font-size: 10pt;
            font-style: normal;
            text-align: center;
            vertical-align: middle;
            overflow: visible;
            border-left: #000000 1px solid;
            border-top: #000000 1px solid;
            border-bottom: #000000 1px solid;
            border-right: #000000 1px solid;
        }

        tr.R17 {
            height: 33px;
        }

        tr.R17 td.R17C0 {
            font-family: Microsoft Sans Serif;
            font-size: 10pt;
            font-style: normal;
            color: #a0522d;
            text-align: center;
            vertical-align: middle;
            border-left: #000000 1px solid;
            border-top: #000000 1px solid;
            border-bottom: #000000 1px solid;
            border-right: #000000 1px solid;
        }

        tr.R17 td.R17C7 {
            font-family: Microsoft Sans Serif;
            font-size: 10pt;
            font-style: normal;
            color: #a0522d;
            text-align: left;
            vertical-align: middle;
            border-left: #000000 1px solid;
            border-top: #000000 1px solid;
            border-bottom: #000000 1px solid;
            border-right: #000000 1px solid;
        }

        table {
            table-layout: fixed;
            padding: 0px;
            padding-left: 2px;
            vertical-align: bottom;
            border-collapse: collapse;
            width: 100%;
            font-family: Arial;
            font-size: 8pt;
            font-style: normal;
        }

        td {
            padding: 0px;
            padding-left: 2px;
            overflow: hidden;
        }

        .panel-collapse {
            overflow: auto;
        }
    </STYLE>
    <div class="row">
        <div class="col-lg-9">
            <?php
            if (!is_array($data)) {
                echo $data;
            } else { ?>
                <?php foreach ($data as $key => $report) { ?>
                    <div class="panel-group" id="accordion">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <a data-toggle="collapse" data-parent="#accordion" href="#collapse<?= $key ?>">
                                    <h4 class="panel-title">
                                        <?= $report['name'] ?>
                                    </h4>
                                </a>
                            </div>
                            <div id="collapse<?= $key ?>" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <?= $report['content'] ?>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php } ?>
            <?php } ?>
        </div>
        <div class="col-lg-3 fixed-block">
            <div class="menu">
                <?= Nav::widget([
                    'options' => ['class' => 'nav-pills nav-stacked nav-stat'],
                    'activateParents' => true,
                    'items' => [
                        [
                            'label' => 'СТАТИСТИКА ЗАЯВЛЕНИЙ',
                            'items' => [
                                ['label' => 'Очная', 'url' => ['site/statistic', 'form' => 'ochnoe']],
                                ['label' => 'Заочная', 'url' => ['site/statistic', 'form' => 'zaochnoe']],
                                ['label' => 'Очно-заочная', 'url' => ['site/statistic', 'form' => 'ochno-zaochnoe']],
                            ]
                        ],
//                        [
//                            'label' => 'СПИСКИ АБИТУРИЕНТОВ С БАЛЛАМИ И ВЫБРАННЫМИ НАПРАВЛЕНИЯМИ ПОДГОТОВКИ',
//                            'items' => [
//                                ['label' => 'Очная форма обучения', 'url' => ['site/abits-list', 'form' => 1, 'skillid' => 0, 'sort' => 0]],
//                                ['label' => 'Очная форма обучения. Магистратура', 'url' => ['site/abits-list', 'form' => 1, 'skillid' => 68]],
//                                ['label' => 'Очная форма обучения. Аспирантура', 'url' => ['site/abits-list', 'form' => 1, 'skillid' => 70]],
//                                ['label' => 'Заочная форма обучения', 'url' => ['site/abits-list', 'form' => 2, 'skillid' => 0, 'sort' => 0]],
//                                ['label' => 'Заочная форма обучения. Магистратура', 'url' => ['site/abits-list', 'form' => 2, 'skillid' => 68]],
//                                ['label' => 'Заочная форма обучения. Аспирантура', 'url' => ['site/abits-list', 'form' => 2, 'skillid' => 70]],
//                                ['label' => 'Очно-заочная форма обучения', 'url' => ['site/abits-list', 'form' => 3, 'skillid' => 0, 'ext' => 0, 'sort' => 0]],
//                            ]
//                        ],
//                        [
//                            'label' => 'СПИСКИ АБИТУРИЕНТОВ С БАЛЛАМИ И ВЫБРАННЫМИ НАПРАВЛЕНИЯМИ ПОДГОТОВКИ, УПОРЯДОЧЕННЫЕ ПО ФАКТУ ПРЕДОСТАВЛЕНИЯ ОРИГИНАЛА ДОКУМЕНТА ОБ ОБРАЗОВАНИИ, КАТЕГОРИИ ПОСТУПЛЕНИЯ И КОНКУРСНЫМ БАЛЛАМ',
//                            'items' => [
//                                ['label' => 'Очная форма обучения', 'url' => ['site/abits-list', 'form' => 1, 'skillid' => 0, 'sort' => 1]],
//                                ['label' => 'Заочная форма обучения', 'url' => ['site/abits-list', 'form' => 2, 'skillid' => 0, 'sort' => 1]],
//                                ['label' => 'Очно-заочная форма обучения', 'url' => ['site/abits-list', 'form' => 3, 'skillid' => 0, 'ext' => 0, 'sort' => 1]],
//                            ]
//                        ],
                        ['label' => 'В начало', 'url' => '#'],
                    ],
                ]);
                ?>
            </div>
        </div>
    </div>
</div>

frontend/views/site/statistic.php
<?php

/* @var $this \yii\web\View */

/* @var $content false|string */

use yii\bootstrap\Nav;

$this->params['breadcrumbs'][] = ['label' => $this->title];

?>

<div class="page">
    <div class="row">
        <div class="col-lg-9">
            <?= $content ?>
        </div>
        <div class="col-lg-3 fixed-block">
            <div class="menu">
                <?= Nav::widget([
                    'options' => ['class' => 'nav-pills nav-stacked nav-stat'],
                    'activateParents' => true,
                    'items' => [
                        [
                            'label' => 'СТАТИСТИКА ЗАЯВЛЕНИЙ',
                            'items' => [
                                ['label' => 'Очная', 'url' => ['site/statistics', 'form' => 1]],
                                ['label' => 'Заочная', 'url' => ['site/statistics', 'form' => 2]],
                                ['label' => 'Очно-заочная', 'url' => ['site/statistics', 'form' => 3]],
                            ]
                        ],
                        [
                            'label' => 'СПИСКИ АБИТУРИЕНТОВ С БАЛЛАМИ И ВЫБРАННЫМИ НАПРАВЛЕНИЯМИ ПОДГОТОВКИ',
                            'items' => [
                                ['label' => 'Очная форма обучения', 'url' => ['site/abits-list', 'form' => 1, 'skillid' => 0, 'sort' => 0]],
                                ['label' => 'Очная форма обучения. Магистратура', 'url' => ['site/abits-list', 'form' => 1, 'skillid' => 68]],
                                ['label' => 'Очная форма обучения. Аспирантура', 'url' => ['site/abits-list', 'form' => 1, 'skillid' => 70]],
                                ['label' => 'Заочная форма обучения', 'url' => ['site/abits-list', 'form' => 2, 'skillid' => 0, 'sort' => 0]],
                                ['label' => 'Заочная форма обучения. Магистратура', 'url' => ['site/abits-list', 'form' => 2, 'skillid' => 68]],
                                ['label' => 'Заочная форма обучения. Аспирантура', 'url' => ['site/abits-list', 'form' => 2, 'skillid' => 70]],
                                ['label' => 'Очно-заочная форма обучения', 'url' => ['site/abits-list', 'form' => 3, 'skillid' => 0, 'ext' => 0, 'sort' => 0]],
                            ]
                        ],
                        [
                            'label' => 'СПИСКИ АБИТУРИЕНТОВ С БАЛЛАМИ И ВЫБРАННЫМИ НАПРАВЛЕНИЯМИ ПОДГОТОВКИ, УПОРЯДОЧЕННЫЕ ПО ФАКТУ ПРЕДОСТАВЛЕНИЯ ОРИГИНАЛА ДОКУМЕНТА ОБ ОБРАЗОВАНИИ, КАТЕГОРИИ ПОСТУПЛЕНИЯ И КОНКУРСНЫМ БАЛЛАМ',
                            'items' => [
                                ['label' => 'Очная форма обучения', 'url' => ['site/abits-list', 'form' => 1, 'skillid' => 0, 'sort' => 1]],
                                ['label' => 'Заочная форма обучения', 'url' => ['site/abits-list', 'form' => 2, 'skillid' => 0, 'sort' => 1]],
                                ['label' => 'Очно-заочная форма обучения', 'url' => ['site/abits-list', 'form' => 3, 'skillid' => 0, 'ext' => 0, 'sort' => 1]],
                            ]
                        ],
                        ['label' => 'В начало', 'url' => '#'],
                    ],
                ]);
                ?>
            </div>
        </div>
    </div>
</div>